export const AUTH_TOKEN = 'VIDISPINE-TOKEN';
export const AUTH_USERNAME = 'VIDISPINE-USERNAME';
export const AUTH_RUNAS = 'VIDISPINE-RUNAS';
export const AUTH_VIDISPINE_SERVER_URL = 'VIDISPINE-SERVER-URL';
